name: CI for EC2
on:
  push:
    branches:
      - main

jobs:
  SSH:
    name: SSH Git Pull
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Git Pull in EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd ${{ secrets.WHOOLOOP_BACKEND_FOLDER }}
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            yarn install
            yarn build
            pm2 stop nestJs
            pm2 start nestJs
